/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_penguinz_testopencvndk_OpencvNativeClass */

using namespace cv;
using namespace std;

#ifndef _Included_com_penguinz_testopencvndk_OpencvNativeClass
#define _Included_com_penguinz_testopencvndk_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_penguinz_testopencvndk_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

JNIEXPORT jint JNICALL Java_com_penguinz_testopencvndk_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_penguinz_testopencvndk_OpencvNativeClass_donothing
        (JNIEnv *, jclass, jlong, jlong);

int toGray(Mat img, Mat& gray);

int doNothing(Mat img, Mat& gray);

#ifdef __cplusplus
}
#endif
#endif
