/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_penguinz_testopencvndk_OpencvTest */

using namespace cv;
using namespace std;

#ifndef _Included_com_penguinz_testopencvndk_OpencvTest
#define _Included_com_penguinz_testopencvndk_OpencvTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_penguinz_testopencvndk_OpencvTest
 * Method:    convertGray
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_penguinz_testopencvndk_OpencvTest_convertGray
  (JNIEnv *, jclass, jbyteArray, jlong, jint, jint);

int toGray(Mat img, Mat& gray);

#ifdef __cplusplus
}
#endif
#endif
